# Generated by Django 5.0.3 on 2024-08-25 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitudServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('empresa', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('telefono', models.CharField(max_length=20)),
                ('tipo_servicio', models.CharField(choices=[('web', 'Página Web'), ('app', 'Aplicación Móvil'), ('ambos', 'Página Web y Aplicación Móvil')], max_length=10)),
                ('descripcion', models.TextField()),
                ('presupuesto_estimado', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('en_proceso', 'En Proceso'), ('completado', 'Completado'), ('cancelado', 'Cancelado')], default='pendiente', max_length=20)),
            ],
            options={
                'verbose_name': 'Solicitud de Servicio',
                'verbose_name_plural': 'Solicitudes de Servicio',
            },
        ),
    ]
