# Generated by Django 3.2.10 on 2024-09-09 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paginaweb', '0002_message'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Message',
        ),
    ]
