# Generated by Django 3.2.10 on 2024-09-18 23:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paginaweb', '0003_delete_message'),
        ('paginaweb', '0003_portfolioproject'),
    ]

    operations = [
    ]
